extends: /etc/kraken/config/build-index/base.yaml

backends:
  - namespace: library/.*
    backend:
      registry_tag:
        address: index.docker.io
        security:
          basic:
            username: ""
            password: ""
  - namespace: .*
    backend:
      testfs:
        addr: kraken-testfs:80
        root: tags
        name_path: docker_tag

cluster:
  hosts:
    static:
      - kraken-build-index-0:80

origin:
  hosts:
    static:
      - kraken-origin-0:80

remotes: {}

tag_replication:
  retry_interval: 100ms
  poll_retries_interval: 250ms

tag_types:
  - namespace: .*
    type: docker
    root: tags

tag_store:
  write_through: false

writeback:
  retry_interval: 100ms
  poll_retries_interval: 250ms

nginx:
  cache_dir: /tmp/kraken-build-index-nginx/

tls:
  client:
    disabled: true
  server:
    disabled: true
