extends: /etc/kraken/config/proxy/base.yaml

origin:
  hosts:
    static:
      - kraken-origin-0:80

build_index:
  hosts:
    static:
      - kraken-build-index-0:80

nginx:
  cache_dir: /tmp/kraken-proxy-nginx/

tls:
  client:
    disabled: true
  server:
    disabled: true
