extends: /etc/kraken/config/tracker/base.yaml

peerstore:
  redis:
    addr: 127.0.0.1:6379

origin:
  hosts:
    static:
      - kraken-origin-0:80

trackerserver:
  announce_interval: 3s

nginx:
  cache_dir: /tmp/kraken-tracker-nginx/

tls:
  client:
    disabled: true
  server:
    disabled: true
