// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/utils/dedup (interfaces: IntervalTask)

// Package mockdedup is a generated GoMock package.
package mockdedup

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIntervalTask is a mock of IntervalTask interface
type MockIntervalTask struct {
	ctrl     *gomock.Controller
	recorder *MockIntervalTaskMockRecorder
}

// MockIntervalTaskMockRecorder is the mock recorder for MockIntervalTask
type MockIntervalTaskMockRecorder struct {
	mock *MockIntervalTask
}

// NewMockIntervalTask creates a new mock instance
func NewMockIntervalTask(ctrl *gomock.Controller) *MockIntervalTask {
	mock := &MockIntervalTask{ctrl: ctrl}
	mock.recorder = &MockIntervalTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIntervalTask) EXPECT() *MockIntervalTaskMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockIntervalTask) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run
func (mr *MockIntervalTaskMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIntervalTask)(nil).Run))
}
