// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/lib/hashring (interfaces: PassiveRing)

// Package mockhashring is a generated GoMock package.
package mockhashring

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/uber/kraken/core"
	stringset "github.com/uber/kraken/utils/stringset"
)

// MockPassiveRing is a mock of PassiveRing interface.
type MockPassiveRing struct {
	ctrl     *gomock.Controller
	recorder *MockPassiveRingMockRecorder
}

// MockPassiveRingMockRecorder is the mock recorder for MockPassiveRing.
type MockPassiveRingMockRecorder struct {
	mock *MockPassiveRing
}

// NewMockPassiveRing creates a new mock instance.
func NewMockPassiveRing(ctrl *gomock.Controller) *MockPassiveRing {
	mock := &MockPassiveRing{ctrl: ctrl}
	mock.recorder = &MockPassiveRingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPassiveRing) EXPECT() *MockPassiveRingMockRecorder {
	return m.recorder
}

// Contains mocks base method.
func (m *MockPassiveRing) Contains(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Contains", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Contains indicates an expected call of Contains.
func (mr *MockPassiveRingMockRecorder) Contains(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Contains", reflect.TypeOf((*MockPassiveRing)(nil).Contains), arg0)
}

// Failed mocks base method.
func (m *MockPassiveRing) Failed(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Failed", arg0)
}

// Failed indicates an expected call of Failed.
func (mr *MockPassiveRingMockRecorder) Failed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Failed", reflect.TypeOf((*MockPassiveRing)(nil).Failed), arg0)
}

// Locations mocks base method.
func (m *MockPassiveRing) Locations(arg0 core.Digest) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locations", arg0)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Locations indicates an expected call of Locations.
func (mr *MockPassiveRingMockRecorder) Locations(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locations", reflect.TypeOf((*MockPassiveRing)(nil).Locations), arg0)
}

// Members mocks base method.
func (m *MockPassiveRing) Members() stringset.Set {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Members")
	ret0, _ := ret[0].(stringset.Set)
	return ret0
}

// Members indicates an expected call of Members.
func (mr *MockPassiveRingMockRecorder) Members() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Members", reflect.TypeOf((*MockPassiveRing)(nil).Members))
}

// Monitor mocks base method.
func (m *MockPassiveRing) Monitor(arg0 <-chan struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Monitor", arg0)
}

// Monitor indicates an expected call of Monitor.
func (mr *MockPassiveRingMockRecorder) Monitor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Monitor", reflect.TypeOf((*MockPassiveRing)(nil).Monitor), arg0)
}

// Refresh mocks base method.
func (m *MockPassiveRing) Refresh() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Refresh")
}

// Refresh indicates an expected call of Refresh.
func (mr *MockPassiveRingMockRecorder) Refresh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockPassiveRing)(nil).Refresh))
}
