# GoLand-style linting configuration
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

linters-settings:
  gofumpt:
    # Use extra rules for cleaner code (GoLand style)
    extra-rules: true
    
  goimports:
    # Group imports like GoLand
    local-prefixes: github.com/uber/kraken
    
  gci:
    # Import grouping (GoLand style)
    sections:
      - standard
      - default
      - prefix(github.com/uber/kraken)
    skip-generated: true
    
  misspell:
    locale: US
    
  govet:
    check-shadowing: true
    enable-all: true
    
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

linters:
  enable:
    - gofumpt      # Stricter gofmt (GoLand-like)
    - goimports    # Import management
    - gci          # Import grouping
    - misspell     # Spell checking
    - revive       # Enhanced go vet
    - govet        # Standard vet
    - ineffassign  # Detect ineffective assignments
    - typecheck    # Type checking
    - unused       # Detect unused code
    - gosimple     # Simplify code
    - staticcheck  # Static analysis
    - unconvert    # Remove unnecessary conversions
    - unparam      # Detect unused parameters
    - gocyclo      # Cyclomatic complexity
    - goconst      # Detect repeated strings
    - gocritic     # Comprehensive checks
    
  disable:
    - errcheck     # Can be noisy
    - gosec        # Security (enable if needed)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - dupl
        - goconst