extends: base.yaml

peerstore:
  redis:
    addr: 127.0.0.1:14001

origin:
  hosts:
    static:
      - host.docker.internal:15002

trackerserver:
  announce_interval: 3s

nginx:
  cache_dir: /tmp/kraken-tracker-nginx/

tls:
  name: kraken
  cas:
  - path: /etc/kraken/tls/ca/server.crt
  server:
    cert:
      path: /etc/kraken/tls/ca/server.crt
    key:
      path: /etc/kraken/tls/ca/server.key
    passphrase:
      path: /etc/kraken/tls/ca/passphrase
  client:
    cert:
      path: /etc/kraken/tls/client/client.crt
    key:
      path: /etc/kraken/tls/client/client.key
    passphrase:
      path: /etc/kraken/tls/client/passphrase
