// Copyright (c) 2019 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/build-index/tagtype (interfaces: DependencyResolver)

// Package mocktagtype is a generated GoMock package.
package mocktagtype

import (
	gomock "github.com/golang/mock/gomock"
	core "github.com/uber/kraken/core"
	reflect "reflect"
)

// MockDependencyResolver is a mock of DependencyResolver interface
type MockDependencyResolver struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyResolverMockRecorder
}

// MockDependencyResolverMockRecorder is the mock recorder for MockDependencyResolver
type MockDependencyResolverMockRecorder struct {
	mock *MockDependencyResolver
}

// NewMockDependencyResolver creates a new mock instance
func NewMockDependencyResolver(ctrl *gomock.Controller) *MockDependencyResolver {
	mock := &MockDependencyResolver{ctrl: ctrl}
	mock.recorder = &MockDependencyResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDependencyResolver) EXPECT() *MockDependencyResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method
func (m *MockDependencyResolver) Resolve(arg0 string, arg1 core.Digest) (core.DigestList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", arg0, arg1)
	ret0, _ := ret[0].(core.DigestList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve
func (mr *MockDependencyResolverMockRecorder) Resolve(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockDependencyResolver)(nil).Resolve), arg0, arg1)
}
