// Code generated by MockGen. DO NOT EDIT.
// Source: code.uber.internal/infra/kraken/origin/blobserver (interfaces: Client)

// Package mockblobserver is a generated GoMock package.
package mockblobserver

import (
	image "code.uber.internal/infra/kraken/lib/dockerregistry/image"
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CheckBlob mocks base method
func (m *MockClient) CheckBlob(arg0 image.Digest) error {
	ret := m.ctrl.Call(m, "CheckBlob", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckBlob indicates an expected call of CheckBlob
func (mr *MockClientMockRecorder) CheckBlob(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBlob", reflect.TypeOf((*MockClient)(nil).CheckBlob), arg0)
}

// CommitUpload mocks base method
func (m *MockClient) CommitUpload(arg0 image.Digest, arg1 string) error {
	ret := m.ctrl.Call(m, "CommitUpload", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitUpload indicates an expected call of CommitUpload
func (mr *MockClientMockRecorder) CommitUpload(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitUpload", reflect.TypeOf((*MockClient)(nil).CommitUpload), arg0, arg1)
}

// DeleteBlob mocks base method
func (m *MockClient) DeleteBlob(arg0 image.Digest) error {
	ret := m.ctrl.Call(m, "DeleteBlob", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlob indicates an expected call of DeleteBlob
func (mr *MockClientMockRecorder) DeleteBlob(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlob", reflect.TypeOf((*MockClient)(nil).DeleteBlob), arg0)
}

// GetBlob mocks base method
func (m *MockClient) GetBlob(arg0 image.Digest) (io.Reader, error) {
	ret := m.ctrl.Call(m, "GetBlob", arg0)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlob indicates an expected call of GetBlob
func (mr *MockClientMockRecorder) GetBlob(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlob", reflect.TypeOf((*MockClient)(nil).GetBlob), arg0)
}

// PatchUpload mocks base method
func (m *MockClient) PatchUpload(arg0 image.Digest, arg1 string, arg2, arg3 int64, arg4 io.Reader) error {
	ret := m.ctrl.Call(m, "PatchUpload", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchUpload indicates an expected call of PatchUpload
func (mr *MockClientMockRecorder) PatchUpload(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchUpload", reflect.TypeOf((*MockClient)(nil).PatchUpload), arg0, arg1, arg2, arg3, arg4)
}

// Repair mocks base method
func (m *MockClient) Repair() (io.Reader, error) {
	ret := m.ctrl.Call(m, "Repair")
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Repair indicates an expected call of Repair
func (mr *MockClientMockRecorder) Repair() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repair", reflect.TypeOf((*MockClient)(nil).Repair))
}

// UploadBlob mocks base method
func (m *MockClient) UploadBlob(arg0 image.Digest) (string, error) {
	ret := m.ctrl.Call(m, "UploadBlob", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadBlob indicates an expected call of UploadBlob
func (mr *MockClientMockRecorder) UploadBlob(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadBlob", reflect.TypeOf((*MockClient)(nil).UploadBlob), arg0)
}
