zap:
  level: info
  development: false
  encoding: console
  disableStacktrace: true
  encoderConfig:
    messageKey: message
    nameKey: logger_name
    levelKey: level
    timeKey: ts
    callerKey: caller
    stacktraceKey: stack
    levelEncoder: capital
    timeEncoder: iso8601
    durationEncoder: seconds
    callerEncoder: short
  outputPaths:
    - stdout
    - /var/log/kraken/kraken-origin/stdout.log
  errorOutputPaths:
    - stdout
    - /var/log/kraken/kraken-origin/stdout.log

metainfogen:
  piece_lengths:
    0: 4MB # Use 4MB piece lengths for all file sizes (for now).

peer_id_factory: addr_hash

scheduler:
  log:
    timeEncoder: iso8601
  torrentlog:
    disable: true

localdb:
  source: /var/cache/kraken/kraken-origin/origin.db

blobstore:
  disk_store:
    capacity: 209715200 # 200MB, placeholder
    root_dir: /var/cache/kraken/kraken-origin/cache/
    reboot_incomplete_blobs: false
    shard_length: 2
  memory_store:
    capacity_bytes: 1048576 # 1MB, placeholder
    gomemlimit_bytes: 536870912 # 512MB, placeholder
  num_flush_workers: 10

blobserver:
  listener:
    net: unix
    addr: /tmp/kraken-origin.sock

nginx:
  name: kraken-origin
  cache_dir: /var/cache/kraken/kraken-origin/nginx/
  log_dir: /var/log/kraken/kraken-origin/
