// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/lib/torrent/scheduler (interfaces: Scheduler)

// Package mockscheduler is a generated GoMock package.
package mockscheduler

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/uber/kraken/core"
	scheduler "github.com/uber/kraken/lib/torrent/scheduler"
	connstate "github.com/uber/kraken/lib/torrent/scheduler/connstate"
	storage "github.com/uber/kraken/lib/torrent/storage"
)

// MockScheduler is a mock of Scheduler interface
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// BlacklistSnapshot mocks base method
func (m *MockScheduler) BlacklistSnapshot() ([]connstate.BlacklistedConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlacklistSnapshot")
	ret0, _ := ret[0].([]connstate.BlacklistedConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlacklistSnapshot indicates an expected call of BlacklistSnapshot
func (mr *MockSchedulerMockRecorder) BlacklistSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlacklistSnapshot", reflect.TypeOf((*MockScheduler)(nil).BlacklistSnapshot))
}

// Download mocks base method
func (m *MockScheduler) Download(arg0 string, arg1 core.Digest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Download indicates an expected call of Download
func (mr *MockSchedulerMockRecorder) Download(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockScheduler)(nil).Download), arg0, arg1)
}

// DownloadReader mocks base method
func (m *MockScheduler) DownloadReader(arg0 string, arg1 core.Digest) (scheduler.BlobReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadReader", arg0, arg1)
	ret0, _ := ret[0].(scheduler.BlobReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadReader indicates an expected call of DownloadReader
func (mr *MockSchedulerMockRecorder) DownloadReader(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadReader", reflect.TypeOf((*MockScheduler)(nil).DownloadReader), arg0, arg1)
}

// Probe mocks base method
func (m *MockScheduler) Probe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probe")
	ret0, _ := ret[0].(error)
	return ret0
}

// Probe indicates an expected call of Probe
func (mr *MockSchedulerMockRecorder) Probe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockScheduler)(nil).Probe))
}

// RemoveTorrent mocks base method
func (m *MockScheduler) RemoveTorrent(arg0 core.Digest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTorrent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTorrent indicates an expected call of RemoveTorrent
func (mr *MockSchedulerMockRecorder) RemoveTorrent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTorrent", reflect.TypeOf((*MockScheduler)(nil).RemoveTorrent), arg0)
}

// Stop mocks base method
func (m *MockScheduler) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop
func (mr *MockSchedulerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockScheduler)(nil).Stop))
}

// Stat mocks base method
func (m *MockScheduler) Stat(arg0 string, arg1 core.Digest) (*storage.TorrentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", arg0, arg1)
	ret0, _ := ret[0].(*storage.TorrentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat
func (mr *MockSchedulerMockRecorder) Stat(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockScheduler)(nil).Stat), arg0, arg1)
}

// ReadableRange mocks base method
func (m *MockScheduler) ReadableRange(arg0 string, arg1 core.Digest, arg2, arg3 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadableRange", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadableRange indicates an expected call of ReadableRange
func (mr *MockSchedulerMockRecorder) ReadableRange(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadableRange", reflect.TypeOf((*MockScheduler)(nil).ReadableRange), arg0, arg1, arg2, arg3)
}

// CopyReadyRange mocks base method
func (m *MockScheduler) CopyReadyRange(arg0 string, arg1 core.Digest, arg2 io.Writer, arg3, arg4 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyReadyRange", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyReadyRange indicates an expected call of CopyReadyRange
func (mr *MockSchedulerMockRecorder) CopyReadyRange(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyReadyRange", reflect.TypeOf((*MockScheduler)(nil).CopyReadyRange), arg0, arg1, arg2, arg3, arg4)
}
