// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/origin/blobclient (interfaces: ClusterProvider)

// Package mockblobclient is a generated GoMock package.
package mockblobclient

import (
	gomock "github.com/golang/mock/gomock"
	blobclient "github.com/uber/kraken/origin/blobclient"
	reflect "reflect"
)

// MockClusterProvider is a mock of ClusterProvider interface
type MockClusterProvider struct {
	ctrl     *gomock.Controller
	recorder *MockClusterProviderMockRecorder
}

// MockClusterProviderMockRecorder is the mock recorder for MockClusterProvider
type MockClusterProviderMockRecorder struct {
	mock *MockClusterProvider
}

// NewMockClusterProvider creates a new mock instance
func NewMockClusterProvider(ctrl *gomock.Controller) *MockClusterProvider {
	mock := &MockClusterProvider{ctrl: ctrl}
	mock.recorder = &MockClusterProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClusterProvider) EXPECT() *MockClusterProviderMockRecorder {
	return m.recorder
}

// Provide mocks base method
func (m *MockClusterProvider) Provide(arg0 string) (blobclient.ClusterClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provide", arg0)
	ret0, _ := ret[0].(blobclient.ClusterClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Provide indicates an expected call of Provide
func (mr *MockClusterProviderMockRecorder) Provide(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provide", reflect.TypeOf((*MockClusterProvider)(nil).Provide), arg0)
}
